### ISSUE TITLE
create-with-format does not accept single-digit days, hours, minutes, or seconds, for datetime or date logotimes

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#14]
Here's the code:
      set the-logotime time:create-with-format the-time-string "MM/dd/yyyy HH:mm:ss.SSS"
and here's example results:

Year | Month | Day | Hour | Minute | Second | Millisecond | Input string | Output string
1680 | 12 | 31 | 6 | 28 | 14 | 438 | 12/31/1680 6:28:14.438 | Extension exception: Time extension could not parse input
2548 | 12 | 31 | 3 | 59 | 55 | 27 | 12/31/2548 3:59:55.027 | Extension exception: Time extension could not parse input
2160 | 12 | 31 | 19 | 33 | 32 | 701 | 12/31/2160 19:33:32.701 | 33:32.7
2424 | 12 | 31 | 9 | 43 | 56 | 535 | 12/31/2424 9:43:56.535 | Extension exception: Time extension could not parse input
2304 | 12 | 31 | 14 | 42 | 27 | 431 | 12/31/2304 14:42:27.431 | 42:27.4
2725 | 12 | 31 | 23 | 2 | 50 | 118 | 12/31/2725 23:2:50.118 | Extension exception: Time extension could not parse input
1827 | 12 | 31 | 16 | 39 | 44 | 17 | 12/31/1827 16:39:44.017 | 1827-12-31 16:39:44.017
2680 | 12 | 31 | 20 | 51 | 52 | 618 | 12/31/2680 20:51:52.618 | 51:52.6

**Comment by charlesres** [comment]
Hi @SFRailsback, the issue you are experiencing is from the pattern provided. Since time:create-with-format enforces strict date resolution, single digit values are not allowed, unless the pattern represents that case.
For example, entering:
`let the-logotime time:create-with-format "12/31/1680 12:2:3.200" "M/d/yyy H:m:s.SSS" `
would provide a flexible pattern for one or two digits, while providing the correct date.
 `print time:show the-logotime "M/d/yyy HH:mm:ss.SSS" `
 `output: 12/31/1680 12:02:03.200`

One thing I should mention is that 'S' patterns do not follow the above rule, instead following the strict resolver format. I'll add these rules to the documentation and see if I can add support for flexible millisecond patterns.

**Comment by SFRailsback** [comment]
With my test code, this statement works:
 set the-logotime time:create-with-format the-time-string "M/d/yyyy H:m:s.SSS"
EXCEPT when milliseconds has fewer than 3 digits.

This is a problem because NetLogo seems to always drop zeroes at the end of a number, even when using "precision": this code
  let the-seconds precision (the-second + (the-milliseconds / 1000)) 3
produces values like 23.03 instead of 23.030.
