### ISSUE TITLE
Documentation: days of week start on Saturday

### ISSUE THREAD

**Issue by SFRailsback** [NetLogo/Time-Extension#7]
The documentation for time:get needs to say that time:get "dayofweek" (or "dow", "weekday", "wday") returns a 1 for Saturday, 7 for Friday; this is in contrast to platforms like Excel that treat Sunday as the first day of the week.

**Comment by charlesres** [comment]
Hi @SFRailsback. Thanks for submitting this issue and providing details on weekday. I believe this is a general bug in how weekday appears in LogoTime, since the Java 8 Time Library has Monday assigned as 1 and Sunday as 7. I'll update it to reflect the time library since the extension uses these encodings.

**Comment by SFRailsback** [comment]
At least as of today, time:get returns 1 for Monday, 7 for Sunday. I may have mixed up its behavior when I submitted the issue.

**Comment by charlesres** [comment]
The wiki has been updated to reflect the new behavior.
